version: '3'
services:
  load:
    image: ${REPO}/rs-load:${TAG}
    build:
      context: load-gen
    environment:
      HOST: http://web:8080
    networks:
      - robot-shop
    depends_on:
      - web
