version: '3'
services:
  mongodb:
    build:
      context: mongo
    image: steveww/rs-mongodb
    ports:
      - "27017"
    networks:
      - robot-shop
  redis:
    image: redis:4.0.6
    ports:
      - "6379"
    networks:
      - robot-shop
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672"
      - "15672"
    networks:
      - robot-shop
  catalogue:
    build:
      context: catalogue
    image: steveww/rs-catalogue
    depends_on:
      - mongodb
    ports:
      - "8080"
    networks:
      - robot-shop
  user:
    build:
      context: user
    image: steveww/rs-user
    depends_on:
      - mongodb
      - redis
    ports:
      - "8080"
    networks:
      - robot-shop
  cart:
    build:
      context: cart
    image: steveww/rs-cart
    depends_on:
      - redis
    ports:
      - "8080"
    networks:
      - robot-shop
  mysql:
    build:
      context: shipping/database
    image: steveww/rs-shipping-db
    ports:
      - "3306"
    networks:
      - robot-shop
  shipping:
    build:
      context: shipping/service
    image: steveww/rs-shipping
    depends_on:
      - mysql
    ports:
      - "8080"
    networks:
      - robot-shop
  payment:
    build:
      context: payment
    image: steveww/rs-payment
    depends_on:
      - rabbitmq
    environment:
      - AUTOWRAPT_BOOTSTRAP=flask
    ports:
      - "8080"
    networks:
      - robot-shop
  dispatch:
    build:
      context: dispatch
    image: steveww/rs-dispatch
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
  web:
    build:
      context: web
    image: steveww/rs-web
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - robot-shop

networks:
  robot-shop:

