version: '3'
services:
  shipping:
    build:
      context: .
    image: foo
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - test

  mysql:
    image: robotshop/rs-mysql-db
    cap_add:
      - NET_ADMIN
    networks:
      - test


networks:
  test:
