apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: shipping
  namespace: robot-shop
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: steveww/rs-shipping
          ports:
            - containerPort: 8080
