apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: payment
  name: payment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment
    spec:
      containers:
      - env:
        - name: AUTOWRAPT_BOOTSTRAP
          value: flask
        image: steveww/rs-payment
        name: payment
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
