apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: robotshop/rs-web:0.2.0
        name: web
        # env:
          # - name: INSTANA_EUM_KEY
          # value: <your key here>
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
