[[constraint]]
    name = "github.com/streadway/amqp"
    branch = "master"

[[constraint]]
    name = "github.com/instana/golang-sensor"
    version = "~1.4.11"

[[constraint]]
    name = "github.com/opentracing/opentracing-go"
    version = "~1.0.2"
