[[constraint]]
    name = "github.com/streadway/amqp"
    branch = "master"

[[constraint]]
    name = "github.com/instana/go-sensor"
    version = "~1.4.17"

[[constraint]]
    name = "github.com/opentracing/opentracing-go"
    version = "~1.1.0"
