apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redis"
