apiVersion: v1
kind: Service
metadata:
  labels:
    service: catalogue
  name: catalogue
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: catalogue
status:
  loadBalancer: {}
