apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: catalogue
  name: catalogue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: catalogue
    spec:
      containers:
      - image: robotshop/rs-catalogue:latest
        name: catalogue
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 200m
        #     memory: 100Mi
        #   requests:
        #     cpu: 100m
        #     memory: 50Mi
      restartPolicy: Always
