apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: dispatch
  name: dispatch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dispatch
    spec:
      containers:
      - image: robotshop/rs-dispatch:0.2.0
        name: dispatch
        resources: {}
      restartPolicy: Always
status: {}
