apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: dispatch
  name: dispatch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      containers:
      - image: robotshop/rs-dispatch:latest
        name: dispatch
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
