apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - image: robotshop/rs-mongodb:latest
        name: mongodb
        ports:
        - containerPort: 27017
        # resources:
        #   limits:
        #     cpu: 200m
        #     memory: 200Mi
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
      restartPolicy: Always
