apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mysql
    spec:
      containers:
      - image: robotshop/rs-mysql-db:latest
        name: mysql
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 400Mi
      restartPolicy: Always
