apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  ports:
  - name: "tcp-amqp"
    port: 5672
    targetPort: 5672
  - name: "http-management"
    port: 15672
    targetPort: 15672
  selector:
    service: rabbitmq
