apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: shipping
  name: shipping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: shipping
    spec:
      containers:
      - image: robotshop/rs-shipping:latest
        name: shipping
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always
