apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robot-shop
  labels:
    app: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
